# Generated by Django 2.2.3 on 2019-07-16 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=28)),
                ('last_name', models.CharField(max_length=28)),
                ('relationship', models.CharField(max_length=32)),
                ('mobile_number', models.CharField(max_length=12)),
                ('landline_number', models.CharField(blank=True, max_length=12, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
